name: hcp-vault-configuration
version: 1.3.4
vcsbranch: 
vcsworkingdirectory: 
description: Example of base configuration of HCP Vault
tags:
  - tfc
  - vault
  - deployed
  - configured
  - tfc-config-as-code